import express from 'express';
import { ctrlAuth } from '../../controllers/auth/authController.js';
import { verifyToken } from '../../middlewares/auth.js';
import { authLimiter, authReadLimiter, oauthLimiter, otpLimiter, otpResendLimiter, usernameAvailabilityLimiter } from '../../middlewares/security.js';
import { asyncHandler } from '../../middlewares/asyncHandler.js';
import { turnstileConfig, verifyTurnstile } from '../../middlewares/turnstile.js';

const router = express.Router();
router.post('/login', authLimiter, verifyTurnstile('login'), asyncHandler(ctrlAuth.login));
router.post('/register', authLimiter, verifyTurnstile('register'), asyncHandler(ctrlAuth.register));
router.get('/turnstile/config', authReadLimiter, turnstileConfig);
router.get('/username-availability', usernameAvailabilityLimiter, asyncHandler(ctrlAuth.usernameAvailability));
router.get('/oauth/pending', authLimiter, asyncHandler(ctrlAuth.pendingOAuthRegistration));
router.post('/oauth/complete', authLimiter, asyncHandler(ctrlAuth.completeOAuthRegistration));
router.post('/verify-access', otpLimiter, asyncHandler(ctrlAuth.verifyAccess));
router.post('/resend-access-code', otpResendLimiter, asyncHandler(ctrlAuth.resendAccessCode));
router.get('/me', authReadLimiter, verifyToken, asyncHandler(ctrlAuth.me));
router.post('/logout', authReadLimiter, verifyToken, asyncHandler(ctrlAuth.logout));
router.get('/google/config', authReadLimiter, asyncHandler(ctrlAuth.googleConfig));
router.post('/google', oauthLimiter, asyncHandler(ctrlAuth.googleAuth));
router.post('/google/code', oauthLimiter, asyncHandler(ctrlAuth.googleCodeAuth));
router.get('/twitch/config', authReadLimiter, asyncHandler(ctrlAuth.twitchConfig));
router.get('/twitch', oauthLimiter, asyncHandler(ctrlAuth.twitchStart));
router.get('/twitch/callback', oauthLimiter, asyncHandler(ctrlAuth.twitchCallback));
router.get('/kick/config', authReadLimiter, asyncHandler(ctrlAuth.kickConfig));
router.get('/kick', oauthLimiter, asyncHandler(ctrlAuth.kickStart));
router.get('/kick/callback', oauthLimiter, asyncHandler(ctrlAuth.kickCallback));
router.get('/discord/config', authReadLimiter, asyncHandler(ctrlAuth.discordConfig));
router.get('/discord', oauthLimiter, asyncHandler(ctrlAuth.discordStart));
router.get('/discord/callback', oauthLimiter, asyncHandler(ctrlAuth.discordCallback));
router.post('/forgot-password', authLimiter, verifyTurnstile('forgot_password'), asyncHandler(ctrlAuth.forgotPassword));
router.post('/reset-password', authLimiter, asyncHandler(ctrlAuth.resetPassword));

export default router;
