import express from 'express';
import { ctrlAuth } from '../../controllers/auth/authController.js';
import { verifyToken } from '../../middlewares/auth.js';
import { authLimiter, authReadLimiter, oauthLimiter, otpLimiter, otpResendLimiter, usernameAvailabilityLimiter } from '../../middlewares/security.js';
import { asyncHandler } from '../../middlewares/asyncHandler.js';
import { turnstileConfig, verifyTurnstile } from '../../middlewares/turnstile.js';
import { requireModuleEnabled } from '../../middlewares/moduleAccess.js';

const router = express.Router();
router.post('/login', requireModuleEnabled('login'), authLimiter, verifyTurnstile('login', { allowLoginFailOpen: true }), asyncHandler(ctrlAuth.login));
router.get('/registration-invite/:token', authReadLimiter, asyncHandler(ctrlAuth.registrationInviteStatus));
router.post('/register', authLimiter, verifyTurnstile('register'), asyncHandler(ctrlAuth.register));
router.get('/turnstile/config', authReadLimiter, turnstileConfig);
router.get('/username-availability', usernameAvailabilityLimiter, asyncHandler(ctrlAuth.usernameAvailability));
router.get('/oauth/pending', requireModuleEnabled('registration'), authLimiter, asyncHandler(ctrlAuth.pendingOAuthRegistration));
router.post('/oauth/complete', requireModuleEnabled('registration'), authLimiter, asyncHandler(ctrlAuth.completeOAuthRegistration));
router.post('/verify-access', requireModuleEnabled('login'), otpLimiter, asyncHandler(ctrlAuth.verifyAccess));
router.post('/resend-access-code', requireModuleEnabled('login'), otpResendLimiter, asyncHandler(ctrlAuth.resendAccessCode));
router.get('/me', authReadLimiter, verifyToken, asyncHandler(ctrlAuth.me));
router.post('/logout', authReadLimiter, verifyToken, asyncHandler(ctrlAuth.logout));
router.get('/google/config', authReadLimiter, asyncHandler(ctrlAuth.googleConfig));
router.post('/google', requireModuleEnabled('login'), oauthLimiter, asyncHandler(ctrlAuth.googleAuth));
router.post('/google/code', requireModuleEnabled('login'), oauthLimiter, asyncHandler(ctrlAuth.googleCodeAuth));
router.get('/twitch/config', authReadLimiter, asyncHandler(ctrlAuth.twitchConfig));
router.get('/twitch', requireModuleEnabled('login'), oauthLimiter, asyncHandler(ctrlAuth.twitchStart));
router.get('/twitch/callback', requireModuleEnabled('login'), oauthLimiter, asyncHandler(ctrlAuth.twitchCallback));
router.get('/kick/config', authReadLimiter, asyncHandler(ctrlAuth.kickConfig));
router.get('/kick', requireModuleEnabled('login'), oauthLimiter, asyncHandler(ctrlAuth.kickStart));
router.get('/kick/callback', requireModuleEnabled('login'), oauthLimiter, asyncHandler(ctrlAuth.kickCallback));
router.get('/discord/config', authReadLimiter, asyncHandler(ctrlAuth.discordConfig));
router.get('/discord', requireModuleEnabled('login'), oauthLimiter, asyncHandler(ctrlAuth.discordStart));
router.get('/discord/callback', requireModuleEnabled('login'), oauthLimiter, asyncHandler(ctrlAuth.discordCallback));
router.post('/forgot-password', requireModuleEnabled('login'), authLimiter, verifyTurnstile('forgot_password'), asyncHandler(ctrlAuth.forgotPassword));
router.post('/reset-password', requireModuleEnabled('login'), authLimiter, asyncHandler(ctrlAuth.resetPassword));

export default router;
