import { Router } from 'express';
import { ChannelController } from '../../controllers/channel/channelController.js';
import { verifyToken } from '../../middlewares/auth.js';
import { requireChannelEditor } from '../../middlewares/channelAccess.js';
import { asyncHandler } from '../../middlewares/asyncHandler.js';

const router = Router();
router.use(verifyToken);
router.get('/mine', asyncHandler(ChannelController.mine));
router.get('/featured', asyncHandler(ChannelController.featured));
router.post('/', asyncHandler(ChannelController.create));
router.get('/invitations/pending', asyncHandler(ChannelController.pendingInvitations));
router.post('/invitations/accept', asyncHandler(ChannelController.accept));
router.post('/invitations/:invitationId/accept', asyncHandler(ChannelController.acceptPendingInvitation));
router.post('/invitations/:invitationId/reject', asyncHandler(ChannelController.rejectPendingInvitation));
router.patch('/:channelId', asyncHandler(requireChannelEditor), asyncHandler(ChannelController.update));
router.delete('/:channelId', asyncHandler(requireChannelEditor), asyncHandler(ChannelController.remove));
router.delete('/:channelId/collaboration', asyncHandler(ChannelController.leave));
router.post('/:channelId/invitations', asyncHandler(requireChannelEditor), asyncHandler(ChannelController.invite));
router.get('/:channelId/collaborators', asyncHandler(requireChannelEditor), asyncHandler(ChannelController.collaborators));
router.patch('/:channelId/collaborators/:userId', asyncHandler(requireChannelEditor), asyncHandler(ChannelController.setCollaboratorAccess));
router.delete('/:channelId/collaborators/:userId', asyncHandler(requireChannelEditor), asyncHandler(ChannelController.removeCollaborator));
export default router;
