export function PageHeader({ eyebrow = 'Administración', title, subtitle, actions }) {
  return <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><span className="inline-block text-[11px] font-black uppercase tracking-[.1em] text-zinc-500">{eyebrow}</span><h1 className="mt-1 text-3xl font-black text-zinc-950">{title}</h1>{subtitle && <p className="mt-1 max-w-3xl text-sm text-zinc-600">{subtitle}</p>}</div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</div>;
}

export function Card({ children, className = '' }) { return <section className={`rounded-2xl border border-zinc-200 bg-white p-5 shadow-[0_8px_24px_rgba(0,0,0,0.06)] ${className}`}>{children}</section>; }
export function Button({ children, variant = 'primary', className = '', ...props }) { const styles = variant === 'secondary' ? 'border-zinc-300 bg-white text-zinc-950 hover:bg-zinc-100' : variant === 'danger' ? 'border-red-700 bg-red-700 text-white hover:bg-red-800' : 'border-zinc-950 bg-zinc-950 text-white hover:bg-zinc-800'; return <button className={`inline-flex items-center justify-center gap-2 rounded-md border px-3.5 py-2.5 font-extrabold transition disabled:cursor-not-allowed disabled:opacity-50 ${styles} ${className}`} {...props}>{children}</button>; }
export function Input({ className = '', ...props }) { return <input className={`w-full rounded-md border border-zinc-300 bg-white px-3 py-[11px] text-zinc-950 outline-none transition placeholder:text-zinc-400 focus:border-zinc-950 disabled:cursor-not-allowed disabled:bg-zinc-100 disabled:text-zinc-500 ${className}`} {...props} />; }
export function Textarea({ className = '', ...props }) { return <textarea className={`w-full rounded-md border border-zinc-300 bg-white px-3 py-[11px] text-zinc-950 outline-none transition placeholder:text-zinc-400 focus:border-zinc-950 disabled:cursor-not-allowed disabled:bg-zinc-100 disabled:text-zinc-500 ${className}`} {...props} />; }
export function Select({ className = '', children, ...props }) { return <select className={`w-full rounded-md border border-zinc-300 bg-white px-3 py-[11px] text-zinc-950 outline-none transition focus:border-zinc-950 disabled:cursor-not-allowed disabled:bg-zinc-100 disabled:text-zinc-500 ${className}`} {...props}>{children}</select>; }
export function Field({ label, hint, children }) { return <label className="grid gap-1.5 text-sm font-bold text-zinc-950"><span>{label}</span>{children}{hint && <small className="font-normal text-zinc-500">{hint}</small>}</label>; }
export function Message({ children, tone = 'neutral' }) { if (!children) return null; const style = tone === 'error' ? 'border-red-200 bg-red-50 text-red-900' : tone === 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-zinc-200 bg-zinc-50 text-zinc-800'; return <div className={`rounded-md border px-3 py-2.5 text-sm ${style}`}>{children}</div>; }
export function LoadingState({ label = 'Cargando…' }) { return <div className="rounded-xl border border-dashed border-zinc-300 p-8 text-center text-sm text-zinc-500">{label}</div>; }
export function EmptyState({ title = 'Sin registros', description }) { return <div className="rounded-xl border border-dashed border-zinc-300 p-8 text-center"><strong className="block text-zinc-950">{title}</strong>{description && <span className="mt-1 block text-sm text-zinc-500">{description}</span>}</div>; }
export function Badge({ children, active = true }) { return <span className={`inline-flex rounded-full border px-2 py-1 text-xs font-bold ${active ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-zinc-200 bg-zinc-100 text-zinc-600'}`}>{children}</span>; }
